name: Python package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install MySQL server and client
        run: |
          sudo apt-get update
          sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password your_password_here'
          sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password your_password_here'
          sudo apt-get install -y mysql-server mysql-client
      - name: Start MySQL server
        run: sudo service mysql start
      - name: Create database and user
        env:
          MYSQL_ROOT_PASSWORD: your_password_here
        run: |
          mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE pets;"
          mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "CREATE USER 'newuser'@'localhost' IDENTIFIED BY 'password';"
          mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "GRANT ALL ON pets.* TO 'newuser'@'localhost';"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest
      - name: Stop MySQL server
        run: sudo service mysql stop
